import type { GiftTemplate } from './types';

export const GIFT_TEMPLATES: GiftTemplate[] = [
  {
    slug: 'yes-no',
    name: 'Tanya Dulu',
    description:
      'Satu pertanyaan, dua tombol. Tombol nggak makin kecil setiap ditekan — sampai tersisa satu jawaban.',
    sections: [
      { id: 'basics', label: 'Dasar', fields: ['recipient_name', 'sender_name', 'question'] },
      { id: 'buttons', label: 'Tombol & rayuan', fields: ['yes_label', 'no_label', 'no_lines', 'success_text'] },
      { id: 'letter', label: 'Surat', fields: ['letter', 'letter_style', 'envelope_color', 'stamp_sticker', 'letter_front', 'stamp', 'stamp_custom', 'sticker_set'] },
      { id: 'photos', label: 'Foto', fields: ['photos'] },
      {
        id: 'music',
        label: 'Musik',
        fields: ['song_title', 'song_artist', 'song_source', 'youtube_url', 'mp3_url', 'trim_song', 'yt_start', 'yt_end', 'lyrics'],
      },
      { id: 'extras', label: 'Sentuhan akhir', fields: ['meet_date', 'theme'] },
    ],
    fields: [
      { key: 'recipient_name', label: 'Nama dia', placeholder: 'Ara', type: 'text', required: true, maxLength: 40 },
      { key: 'sender_name', label: 'Nama kamu', placeholder: 'Dim', type: 'text', maxLength: 40 },
      {
        key: 'question',
        label: 'Pertanyaanmu',
        placeholder: 'Mau tau ga isinya apa',
        type: 'text',
        required: true,
        maxLength: 120,
      },
      {
        key: 'photos',
        label: 'Foto kalian (maks 4)',
        type: 'photo-gallery',
        maxItems: 4,
        slotHints: [
          'Kartu perayaan, piringan lagu & surat',
          'Halaman foto surat',
          'Halaman foto surat',
          'Halaman foto surat',
        ],
        help: 'Geser urutan dengan tombol ‹ ›. Perlu masuk dulu untuk mengunggah. Kosongkan untuk memakai maskot bawaan.',
      },
      { key: 'yes_label', label: 'Tombol iya', placeholder: 'Mau', type: 'text', maxLength: 20 },
      { key: 'no_label', label: 'Tombol nggak', placeholder: 'Nggak', type: 'text', maxLength: 20 },
      {
        key: 'no_lines',
        label: 'Rayuan tiap dia coba pencet tombol nggak',
        type: 'textarea',
        maxLength: 600,
        help: 'Satu baris untuk satu percobaan, lalu berulang dari awal. Tombol nggak makin kecil tiap dicoba — tidak akan pernah bisa ditekan.',
      },
      { key: 'success_text', label: 'Teks perayaan', placeholder: 'AKU TAHU KAMU BAKAL BILANG IYA', type: 'text', maxLength: 80 },
      {
        key: 'letter',
        label: 'Suratmu',
        type: 'textarea',
        required: true,
        maxLength: 400,
        help: 'Dibuka setelah dia menjawab iya. Ditulis dengan huruf tangan. Maksimal 400 karakter — yang pendek justru lebih kena.',
        maxWords: 200,
        help: 'Dibuka setelah dia menjawab iya. Ditulis dengan huruf tangan.',
      },
      {
        key: 'letter_style',
        label: 'Gaya kertas surat',
        type: 'select',
        options: [
          { value: 'plain', label: 'Polos' },
          { value: 'ruled', label: 'Bergaris' },
          { value: 'vintage', label: 'Vintage' },
        ],
      },
      {
        key: 'envelope_color',
        label: 'Desain amplop',
        type: 'select',
        options: [
          { value: 'cream', label: 'Krem' },
          { value: 'rose', label: 'Merah muda' },
          { value: 'kraft', label: 'Kraft' },
          { value: 'sky', label: 'Biru langit' },
          { value: 'airmail', label: 'Pos udara' },
          { value: 'airmail-bold', label: 'Pos udara tebal' },
        ],
      },
      {
        key: 'stamp_sticker',
        label: 'Prangko amplop',
        type: 'select',
        options: [
          { value: 'bloom', label: 'Bunga' },
          { value: 'crane', label: 'Bangau origami' },
        ],
        help: 'Menempel di depan amplop, menggantikan nama penerima.',
      },
      {
        key: 'letter_front',
        label: 'Sampul surat',
        type: 'select',
        options: [
          { value: 'classic', label: 'Klasik' },
          { value: 'stars', label: 'Bintang' },
          { value: 'hearts', label: 'Hati' },
        ],
      },
      {
        key: 'stamp',
        label: 'Stempel dekat tanda tangan',
        type: 'select',
        options: [
          { value: 'love', label: 'Made with love' },
          { value: 'original', label: 'Original' },
          { value: 'none', label: 'Tanpa stempel' },
        ],
      },
      {
        key: 'stamp_custom',
        label: 'Stempel / TTD sendiri',
        type: 'photo-gallery',
        maxItems: 1,
        slotHints: ['Dipakai menggantikan stempel bawaan'],
        help: 'Unggah PNG latar transparan (atau foto tanda tangan di kertas putih). Menggantikan pilihan stempel di atas. Perlu masuk dulu untuk mengunggah.',
      },
      {
        key: 'sticker_set',
        label: 'Stiker surat',
        type: 'select',
        options: [
          { value: 'blooms', label: 'Bunga ume' },
          { value: 'cranes', label: 'Bangau origami' },
          { value: 'marks', label: 'Tanda register' },
          { value: 'none', label: 'Tanpa stiker' },
        ],
      },
      { key: 'song_title', label: 'Judul lagu', placeholder: 'Bombay Dreams', type: 'text', maxLength: 60 },
      { key: 'song_artist', label: 'Penyanyi', placeholder: 'KSHMR', type: 'text', maxLength: 60 },
      {
        key: 'song_source',
        label: 'Lagunya dari mana',
        type: 'select',
        options: [
          { value: 'youtube', label: 'Tautan YouTube' },
          { value: 'mp3', label: 'Unggah MP3' },
        ],
      },
      {
        key: 'youtube_url',
        label: 'Tautan YouTube',
        type: 'url',
        placeholder: 'https://youtu.be/…',
        showWhen: { key: 'song_source', equals: 'youtube' },
        help: 'Lagunya langsung bisa diputar dari dalam hadiah. Teks (CC) otomatis menyala.',
      },
      {
        key: 'mp3_url',
        label: 'Berkas MP3',
        type: 'audio',
        showWhen: { key: 'song_source', equals: 'mp3' },
        help: 'Format MP3 atau M4A, maksimal 10 MB dan 5 menit. Perlu masuk dulu untuk mengunggah.',
      },
      {
        key: 'trim_song',
        label: 'Potong lagunya',
        type: 'toggle',
        help: 'Nyalakan kalau mau memutar bagian tertentu saja.',
      },
      {
        key: 'yt_start',
        label: 'Mulai dari',
        type: 'text',
        placeholder: '0:45',
        maxLength: 8,
        showWhen: { key: 'trim_song', equals: '1' },
        help: 'Format menit:detik.',
      },
      {
        key: 'yt_end',
        label: 'Berhenti di',
        type: 'text',
        placeholder: '1:30',
        maxLength: 8,
        showWhen: { key: 'trim_song', equals: '1' },
      },
      {
        key: 'lyrics',
        label: 'Lirik lagu (opsional)',
        type: 'textarea',
        maxLength: 800,
        help: 'Satu baris per lirik. Muncul di balik surat seperti tampilan lirik berjalan.',
      },
      {
        key: 'meet_date',
        label: 'Tanggal ketemu berikutnya (opsional)',
        type: 'date',
        help: 'Kaado menghitung mundur harinya untuk kalian.',
      },
      {
        key: 'theme',
        label: 'Tema warna',
        type: 'select',
        options: [
          { value: 'rose', label: 'Romantic Rose' },
          { value: 'ocean', label: 'Ocean Breeze' },
          { value: 'sunset', label: 'Golden Sunset' },
          { value: 'lavender', label: 'Lavender Dream' },
        ],
      },
    ],
    defaults: {
      recipient_name: '',
      sender_name: '',
      question: 'Mau tau ga isinya apa',
      photos: '',
      yes_label: 'Mau',
      no_label: 'Nggak',
      no_lines: [
        'Yakin? udah capek2 bikin nih :")',
        'minimal liat dulu lahh',
        'parah parah',
        'etttt',
        ':((',
        'udah klik iya aja lahh',
        'haha ilang kan button nya',
      ].join('\n'),
      success_text: 'WKWKWK BAGUS',
      letter:
        'Jarak segini cuma angka di peta.\nga harus secara langsung utk bisa ngasih sesuatu hehe\nSelamat yaa, kamu berhasil dapetin hadiah ini. Semoga bisa bikin kamu senyum-senyum sendiri wkwkwk\n',
      letter_style: 'plain',
      envelope_color: 'cream',
      stamp_sticker: 'bloom',
      letter_front: 'classic',
      stamp: 'love',
      stamp_custom: '',
      sticker_set: 'blooms',
      lyrics: '',
      song_title: '',
      song_artist: '',
      song_source: 'youtube',
      youtube_url: '',
      mp3_url: '',
      trim_song: '',
      yt_start: '',
      yt_end: '',
      meet_date: '',
      theme: 'rose',
    },
  },
  {
    slug: 'puzzle-box',
    name: 'Kado Puzzle',
    description:
      'Kadonya diantar, jatuh dari langit, lalu dikunci puzzle. Susun lima potongan fotomu untuk membuka isinya.',
    sections: [
      { id: 'basics', label: 'Dasar', fields: ['recipient_name', 'sender_name'] },
      { id: 'puzzle', label: 'Puzzle', fields: ['puzzle_photo'] },
      { id: 'reveal', label: 'Isi kado', fields: ['reveal_photo', 'reveal_text'] },
      {
        id: 'letter',
        label: 'Surat',
        fields: ['letter', 'letter_style', 'letter_front', 'stamp', 'sticker_set', 'letter_photos'],
      },
      { id: 'music', label: 'Musik', fields: ['youtube_url', 'song_file'] },
      { id: 'extras', label: 'Sentuhan akhir', fields: ['meet_date', 'theme'] },
    ],
    fields: [
      { key: 'recipient_name', label: 'Nama dia', placeholder: 'Ara', type: 'text', required: true, maxLength: 40 },
      { key: 'sender_name', label: 'Nama kamu', placeholder: 'Dim', type: 'text', maxLength: 40 },
      {
        key: 'puzzle_photo',
        label: 'Foto puzzle',
        type: 'photo-gallery',
        maxItems: 1,
        slotHints: ['Dipotong jadi enam keping — satu keping sudah terpasang'],
        help: 'Foto lanskap paling pas. Kosongkan untuk memakai puzzle bernomor.',
      },
      {
        key: 'reveal_photo',
        label: 'Gambar atau GIF yang keluar dari kado',
        type: 'photo-gallery',
        maxItems: 1,
        slotHints: ['Muncul saat kadonya terbuka'],
        help: 'GIF juga bisa. Kosongkan untuk memakai maskot bawaan.',
      },
      {
        key: 'reveal_text',
        label: 'Teks saat kado terbuka',
        placeholder: 'KADONYA KEBUKA',
        type: 'text',
        maxLength: 80,
      },
      {
        key: 'letter',
        label: 'Suratmu',
        type: 'textarea',
        required: true,
        maxWords: 200,
        help: 'Dibuka setelah puzzlenya selesai. Ditulis dengan huruf tangan.',
      },
      {
        key: 'letter_style',
        label: 'Gaya kertas surat',
        type: 'select',
        options: [
          { value: 'crumple', label: 'Lecek' },
          { value: 'plain', label: 'Polos' },
          { value: 'ruled', label: 'Bergaris' },
          { value: 'vintage', label: 'Vintage' },
        ],
      },
      {
        key: 'letter_front',
        label: 'Sampul surat',
        type: 'select',
        options: [
          { value: 'classic', label: 'Klasik' },
          { value: 'stars', label: 'Bintang' },
          { value: 'hearts', label: 'Hati' },
        ],
      },
      {
        key: 'stamp',
        label: 'Stempel dekat tanda tangan',
        type: 'select',
        options: [
          { value: 'love', label: 'Made with love' },
          { value: 'original', label: 'Original' },
          { value: 'none', label: 'Tanpa stempel' },
        ],
      },
      {
        key: 'sticker_set',
        label: 'Stiker surat',
        type: 'select',
        options: [
          { value: 'hearts', label: 'Hati' },
          { value: 'stars', label: 'Bintang' },
          { value: 'blooms', label: 'Bunga' },
          { value: 'none', label: 'Tanpa stiker' },
        ],
      },
      {
        key: 'letter_photos',
        label: 'Foto di dalam surat (maks 3)',
        type: 'photo-gallery',
        maxItems: 3,
        slotHints: ['Halaman foto surat', 'Halaman foto surat', 'Halaman foto surat'],
        help: 'Geser urutan dengan tombol ‹ ›. Perlu masuk dulu untuk mengunggah.',
      },
      {
        key: 'youtube_url',
        label: 'Tautan YouTube (opsional)',
        type: 'url',
        placeholder: 'https://youtu.be/…',
        help: 'Lagunya langsung bisa diputar dari dalam hadiah.',
      },
      {
        key: 'song_file',
        label: 'Unggah lagu (opsional)',
        type: 'audio',
        help: 'Berkas MP3 maksimal 12 MB. Perlu masuk dulu untuk mengunggah. Diputar langsung di dalam hadiah.',
      },
      {
        key: 'meet_date',
        label: 'Tanggal ketemu berikutnya (opsional)',
        type: 'date',
        help: 'Kaado menghitung mundur harinya untuk kalian.',
      },
      {
        key: 'theme',
        label: 'Tema warna',
        type: 'select',
        options: [
          { value: 'rose', label: 'Romantic Rose' },
          { value: 'ocean', label: 'Ocean Breeze' },
          { value: 'sunset', label: 'Golden Sunset' },
          { value: 'lavender', label: 'Lavender Dream' },
        ],
      },
    ],
    defaults: {
      recipient_name: '',
      sender_name: '',
      puzzle_photo: '',
      reveal_photo: '',
      reveal_text: '',
      letter:
        'Kadonya sengaja aku kunci — biar kamu susun dulu potongannya.\nPelan-pelan, sepotong demi sepotong, sampai gambarnya utuh.\nSelamat, kamu berhasil membukanya.',
      letter_style: 'crumple',
      letter_front: 'classic',
      stamp: 'love',
      sticker_set: 'hearts',
      letter_photos: '',
      youtube_url: '',
      song_file: '',
      meet_date: '',
      theme: 'lavender',
    },
  },
];

export function getGiftTemplate(slug: string): GiftTemplate | undefined {
  return GIFT_TEMPLATES.find((t) => t.slug === slug);
}
