import type { GiftTemplate } from './types';

export const GIFT_TEMPLATES: GiftTemplate[] = [
  {
    slug: 'yes-no',
    name: 'Tanya Dulu',
    description:
      'Satu pertanyaan, dua tombol. Tombol nggak makin kecil setiap ditekan — sampai tersisa satu jawaban.',
    sections: [
      { id: 'basics', label: 'Dasar', fields: ['recipient_name', 'sender_name', 'question'] },
      { id: 'buttons', label: 'Tombol & rayuan', fields: ['yes_label', 'no_label', 'no_lines', 'success_text'] },
      { id: 'letter', label: 'Surat', fields: ['letter', 'letter_style', 'envelope_color', 'letter_front', 'stamp', 'sticker_set'] },
      { id: 'photos', label: 'Foto', fields: ['photos'] },
      { id: 'music', label: 'Musik', fields: ['youtube_url', 'song_file'] },
      { id: 'extras', label: 'Sentuhan akhir', fields: ['meet_date', 'theme'] },
    ],
    fields: [
      { key: 'recipient_name', label: 'Nama dia', placeholder: 'Ara', type: 'text', required: true, maxLength: 40 },
      { key: 'sender_name', label: 'Nama kamu', placeholder: 'Dim', type: 'text', maxLength: 40 },
      {
        key: 'question',
        label: 'Pertanyaanmu',
        placeholder: 'Aku kangen. Mau video call bareng malam ini?',
        type: 'text',
        required: true,
        maxLength: 120,
      },
      {
        key: 'photos',
        label: 'Foto kalian (maks 4)',
        type: 'photo-gallery',
        maxItems: 4,
        slotHints: [
          'Kartu perayaan, piringan lagu & surat',
          'Halaman foto surat',
          'Halaman foto surat',
          'Halaman foto surat',
        ],
        help: 'Geser urutan dengan tombol ‹ ›. Perlu masuk dulu untuk mengunggah. Kosongkan untuk memakai maskot bawaan.',
      },
      { key: 'yes_label', label: 'Tombol iya', placeholder: 'Mau', type: 'text', maxLength: 20 },
      { key: 'no_label', label: 'Tombol nggak', placeholder: 'Nggak', type: 'text', maxLength: 20 },
      {
        key: 'no_lines',
        label: 'Rayuan tiap dia menekan nggak',
        type: 'textarea',
        maxLength: 600,
        help: 'Satu baris untuk satu tekanan. Setelah lima kali, tombol nggak menyerah dan hilang.',
      },
      { key: 'success_text', label: 'Teks perayaan', placeholder: 'AKU TAHU KAMU BAKAL BILANG IYA', type: 'text', maxLength: 80 },
      {
        key: 'letter',
        label: 'Suratmu',
        type: 'textarea',
        required: true,
        maxWords: 200,
        help: 'Dibuka setelah dia menjawab iya. Ditulis dengan huruf tangan.',
      },
      {
        key: 'letter_style',
        label: 'Gaya kertas surat',
        type: 'select',
        options: [
          { value: 'plain', label: 'Polos' },
          { value: 'ruled', label: 'Bergaris' },
          { value: 'vintage', label: 'Vintage' },
        ],
      },
      {
        key: 'envelope_color',
        label: 'Warna amplop',
        type: 'select',
        options: [
          { value: 'cream', label: 'Krem' },
          { value: 'rose', label: 'Merah muda' },
          { value: 'kraft', label: 'Kraft' },
          { value: 'sky', label: 'Biru langit' },
        ],
      },
      {
        key: 'letter_front',
        label: 'Sampul surat',
        type: 'select',
        options: [
          { value: 'classic', label: 'Klasik' },
          { value: 'stars', label: 'Bintang' },
          { value: 'hearts', label: 'Hati' },
        ],
      },
      {
        key: 'stamp',
        label: 'Stempel dekat tanda tangan',
        type: 'select',
        options: [
          { value: 'love', label: 'Made with love' },
          { value: 'original', label: 'Original' },
          { value: 'none', label: 'Tanpa stempel' },
        ],
      },
      {
        key: 'sticker_set',
        label: 'Stiker surat',
        type: 'select',
        options: [
          { value: 'hearts', label: 'Hati' },
          { value: 'stars', label: 'Bintang' },
          { value: 'blooms', label: 'Bunga' },
          { value: 'none', label: 'Tanpa stiker' },
        ],
      },
      {
        key: 'youtube_url',
        label: 'Tautan YouTube (opsional)',
        type: 'url',
        placeholder: 'https://youtu.be/…',
        help: 'Lagunya langsung bisa diputar dari dalam hadiah.',
      },
      {
        key: 'song_file',
        label: 'Unggah lagu (opsional)',
        type: 'audio',
        help: 'Berkas MP3 maksimal 12 MB. Perlu masuk dulu untuk mengunggah. Diputar langsung di dalam hadiah.',
      },
      {
        key: 'meet_date',
        label: 'Tanggal ketemu berikutnya (opsional)',
        type: 'date',
        help: 'Kaado menghitung mundur harinya untuk kalian.',
      },
      {
        key: 'theme',
        label: 'Tema warna',
        type: 'select',
        options: [
          { value: 'rose', label: 'Romantic Rose' },
          { value: 'ocean', label: 'Ocean Breeze' },
          { value: 'sunset', label: 'Golden Sunset' },
          { value: 'lavender', label: 'Lavender Dream' },
        ],
      },
    ],
    defaults: {
      recipient_name: '',
      sender_name: '',
      question: 'Aku kangen. Mau nemenin aku video call malam ini?',
      photos: '',
      yes_label: 'Mau',
      no_label: 'Nggak',
      no_lines: [
        'Yakin? Aku udah siapin playlist buat kita berdua…',
        'Hatiku retak pelan-pelan. Kedengeran sampai sana, kan?',
        'Bantalku saja setuju kamu harusnya bilang iya.',
        'Oke, aku mulai panik. Tombolnya makin kecil tuh.',
        'Tombol nggak-nya sudah capek. Tinggal satu pilihan.',
      ].join('\n'),
      success_text: 'AKU TAHU KAMU BAKAL BILANG IYA',
      letter:
        'Jarak segini cuma angka di peta.\nTiap malam aku tetap milih kamu, dari layar kecil ini.\nSampai nanti kita nggak perlu menghitung zona waktu lagi.',
      letter_style: 'plain',
      envelope_color: 'cream',
      letter_front: 'classic',
      stamp: 'love',
      sticker_set: 'hearts',
      youtube_url: '',
      song_file: '',
      meet_date: '',
      theme: 'rose',
    },
  },
  {
    slug: 'puzzle-box',
    name: 'Kado Puzzle',
    description:
      'Kadonya diantar, jatuh dari langit, lalu dikunci puzzle. Susun lima potongan fotomu untuk membuka isinya.',
    sections: [
      { id: 'basics', label: 'Dasar', fields: ['recipient_name', 'sender_name'] },
      { id: 'puzzle', label: 'Puzzle', fields: ['puzzle_photo'] },
      { id: 'reveal', label: 'Isi kado', fields: ['reveal_photo', 'reveal_text'] },
      {
        id: 'letter',
        label: 'Surat',
        fields: ['letter', 'letter_style', 'letter_front', 'stamp', 'sticker_set', 'letter_photos'],
      },
      { id: 'music', label: 'Musik', fields: ['youtube_url', 'song_file'] },
      { id: 'extras', label: 'Sentuhan akhir', fields: ['meet_date', 'theme'] },
    ],
    fields: [
      { key: 'recipient_name', label: 'Nama dia', placeholder: 'Ara', type: 'text', required: true, maxLength: 40 },
      { key: 'sender_name', label: 'Nama kamu', placeholder: 'Dim', type: 'text', maxLength: 40 },
      {
        key: 'puzzle_photo',
        label: 'Foto puzzle',
        type: 'photo-gallery',
        maxItems: 1,
        slotHints: ['Dipotong jadi enam keping — satu keping sudah terpasang'],
        help: 'Foto lanskap paling pas. Kosongkan untuk memakai puzzle bernomor.',
      },
      {
        key: 'reveal_photo',
        label: 'Gambar atau GIF yang keluar dari kado',
        type: 'photo-gallery',
        maxItems: 1,
        slotHints: ['Muncul saat kadonya terbuka'],
        help: 'GIF juga bisa. Kosongkan untuk memakai maskot bawaan.',
      },
      {
        key: 'reveal_text',
        label: 'Teks saat kado terbuka',
        placeholder: 'KADONYA KEBUKA',
        type: 'text',
        maxLength: 80,
      },
      {
        key: 'letter',
        label: 'Suratmu',
        type: 'textarea',
        required: true,
        maxWords: 200,
        help: 'Dibuka setelah puzzlenya selesai. Ditulis dengan huruf tangan.',
      },
      {
        key: 'letter_style',
        label: 'Gaya kertas surat',
        type: 'select',
        options: [
          { value: 'crumple', label: 'Lecek' },
          { value: 'plain', label: 'Polos' },
          { value: 'ruled', label: 'Bergaris' },
          { value: 'vintage', label: 'Vintage' },
        ],
      },
      {
        key: 'letter_front',
        label: 'Sampul surat',
        type: 'select',
        options: [
          { value: 'classic', label: 'Klasik' },
          { value: 'stars', label: 'Bintang' },
          { value: 'hearts', label: 'Hati' },
        ],
      },
      {
        key: 'stamp',
        label: 'Stempel dekat tanda tangan',
        type: 'select',
        options: [
          { value: 'love', label: 'Made with love' },
          { value: 'original', label: 'Original' },
          { value: 'none', label: 'Tanpa stempel' },
        ],
      },
      {
        key: 'sticker_set',
        label: 'Stiker surat',
        type: 'select',
        options: [
          { value: 'hearts', label: 'Hati' },
          { value: 'stars', label: 'Bintang' },
          { value: 'blooms', label: 'Bunga' },
          { value: 'none', label: 'Tanpa stiker' },
        ],
      },
      {
        key: 'letter_photos',
        label: 'Foto di dalam surat (maks 3)',
        type: 'photo-gallery',
        maxItems: 3,
        slotHints: ['Halaman foto surat', 'Halaman foto surat', 'Halaman foto surat'],
        help: 'Geser urutan dengan tombol ‹ ›. Perlu masuk dulu untuk mengunggah.',
      },
      {
        key: 'youtube_url',
        label: 'Tautan YouTube (opsional)',
        type: 'url',
        placeholder: 'https://youtu.be/…',
        help: 'Lagunya langsung bisa diputar dari dalam hadiah.',
      },
      {
        key: 'song_file',
        label: 'Unggah lagu (opsional)',
        type: 'audio',
        help: 'Berkas MP3 maksimal 12 MB. Perlu masuk dulu untuk mengunggah. Diputar langsung di dalam hadiah.',
      },
      {
        key: 'meet_date',
        label: 'Tanggal ketemu berikutnya (opsional)',
        type: 'date',
        help: 'Kaado menghitung mundur harinya untuk kalian.',
      },
      {
        key: 'theme',
        label: 'Tema warna',
        type: 'select',
        options: [
          { value: 'rose', label: 'Romantic Rose' },
          { value: 'ocean', label: 'Ocean Breeze' },
          { value: 'sunset', label: 'Golden Sunset' },
          { value: 'lavender', label: 'Lavender Dream' },
        ],
      },
    ],
    defaults: {
      recipient_name: '',
      sender_name: '',
      puzzle_photo: '',
      reveal_photo: '',
      reveal_text: '',
      letter:
        'Kadonya sengaja aku kunci — biar kamu susun dulu potongannya.\nPelan-pelan, sepotong demi sepotong, sampai gambarnya utuh.\nSelamat, kamu berhasil membukanya.',
      letter_style: 'crumple',
      letter_front: 'classic',
      stamp: 'love',
      sticker_set: 'hearts',
      letter_photos: '',
      youtube_url: '',
      song_file: '',
      meet_date: '',
      theme: 'lavender',
    },
  },
];

export function getGiftTemplate(slug: string): GiftTemplate | undefined {
  return GIFT_TEMPLATES.find((t) => t.slug === slug);
}
