// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (user_id, template_slug, title, slug, status, sections, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, template_slug, title, slug, status, sections, data, access_type, created_at, updated_at
`

type CreateCardParams struct {
	UserID       uuid.UUID `json:"user_id"`
	TemplateSlug string    `json:"template_slug"`
	Title        string    `json:"title"`
	Slug         string    `json:"slug"`
	Status       string    `json:"status"`
	Sections     []byte    `json:"sections"`
	Data         []byte    `json:"data"`
}

type CreateCardRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TemplateSlug string             `json:"template_slug"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Status       string             `json:"status"`
	Sections     []byte             `json:"sections"`
	Data         []byte             `json:"data"`
	AccessType   string             `json:"access_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CreateCardRow, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UserID,
		arg.TemplateSlug,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Sections,
		arg.Data,
	)
	var i CreateCardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateSlug,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Sections,
		&i.Data,
		&i.AccessType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardBySlug = `-- name: GetCardBySlug :one
SELECT id, user_id, template_slug, title, slug, status, sections, data, access_type, created_at, updated_at
FROM cards
WHERE slug = $1 AND status != 'deleted'
LIMIT 1
`

type GetCardBySlugRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TemplateSlug string             `json:"template_slug"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Status       string             `json:"status"`
	Sections     []byte             `json:"sections"`
	Data         []byte             `json:"data"`
	AccessType   string             `json:"access_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCardBySlug(ctx context.Context, slug string) (GetCardBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCardBySlug, slug)
	var i GetCardBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateSlug,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Sections,
		&i.Data,
		&i.AccessType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByUser = `-- name: ListCardsByUser :many
SELECT id, user_id, template_slug, title, slug, status, access_type, created_at, updated_at
FROM cards
WHERE user_id = $1 AND status != 'deleted'
ORDER BY created_at DESC
`

type ListCardsByUserRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TemplateSlug string             `json:"template_slug"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Status       string             `json:"status"`
	AccessType   string             `json:"access_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCardsByUser(ctx context.Context, userID uuid.UUID) ([]ListCardsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsByUserRow{}
	for rows.Next() {
		var i ListCardsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateSlug,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.AccessType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardData = `-- name: UpdateCardData :one
UPDATE cards SET title = $3, data = $4
WHERE slug = $1 AND user_id = $2 AND status != 'deleted'
RETURNING id, user_id, template_slug, title, slug, status, sections, data, access_type, created_at, updated_at
`

type UpdateCardDataParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Data   []byte    `json:"data"`
}

type UpdateCardDataRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TemplateSlug string             `json:"template_slug"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Status       string             `json:"status"`
	Sections     []byte             `json:"sections"`
	Data         []byte             `json:"data"`
	AccessType   string             `json:"access_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCardData(ctx context.Context, arg UpdateCardDataParams) (UpdateCardDataRow, error) {
	row := q.db.QueryRow(ctx, updateCardData,
		arg.Slug,
		arg.UserID,
		arg.Title,
		arg.Data,
	)
	var i UpdateCardDataRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateSlug,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Sections,
		&i.Data,
		&i.AccessType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
