// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TemplateSlug string             `json:"template_slug"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Status       string             `json:"status"`
	LayoutType   *string            `json:"layout_type"`
	Theme        []byte             `json:"theme"`
	AccessType   string             `json:"access_type"`
	AccessSecret *string            `json:"access_secret"`
	Sections     []byte             `json:"sections"`
	Data         []byte             `json:"data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
